### PR TITLE
Update activation documentation

### PR DESCRIPTION
**Pull request by bautrey37**
#### Changes

- add more clarified instructions in Activation/Converting into a license 

#### Checklist

- [x] Read the contribution [guide](../CONTRIBUTING.md) and accept the [code](../CODE_OF_CONDUCT.md) of conduct
- [x] Readme (not needed)
- [x] Tests (not needed)

### CODE REVIEW

**Comment by bautrey37** [comment]
I like your webapp, very nice. 👍  Preview of webapp on PR is very handy. It looks fine to me.

**Review by GabLeRoux — APPROVED** [review]

**Comment by webbertakken** [comment]
This looks incorrect to me. Did you not say you had a pro license? You should probably read the pro section and never do the personal edition step.

**Comment by webbertakken** [comment]
> I like your webapp, very nice. 👍 Preview of webapp on PR is very handy. It looks fine to me.

Thanks! It was actually not much work because vercel is doing all the magic. They're also sponsoring our project.

**Comment by webbertakken** [comment]
I'm closing this, but feel free to reopen if you're still gonna work on it.

**Pull request closed without merging**
