### PR TITLE
WIP: Add gitlab documentation from example project

### PR DESCRIPTION
**Pull request by GabLeRoux**
Adapted parts of the documentation to match an easier to follow getting started guide.

#### Changes

- docs

#### Checklist

- [x] Read the contribution [guide](../CONTRIBUTING.md) and accept the [code](../CODE_OF_CONDUCT.md) of conduct
- [x] Readme (updated or not needed)
- [x] Tests (added, updated or not needed)

### CODE REVIEW

**Comment by GabLeRoux** [comment]
Bash syntax highlighting doesn't seem to work well. Sadly, gitlab example uses bash commands a lot compared to github actions guide.

**Comment by webbertakken** [comment]
Syntax highlighting added in https://github.com/Unity-CI/Website/pull/33

**Comment by webbertakken** [comment]
@GabLeRoux FYI, please retarget to `main`

**Comment by GabLeRoux** [comment]
reopened at #48

**Pull request closed without merging**
